### PR TITLE
feat(spell): update to new mailbox [NET-505]

### PR DESCRIPTION
**Pull request by justprosh**
## Description
Update spells to 0.5.16 version and push to the updated mailbox.

## Motivation
Previously KV was used to mailboxes

## Related Issue(s)
- [NET-496](https://linear.app/fluence/issue/NET-496/rotate-spell-mailbox)
- [NET-505](https://linear.app/fluence/issue/NET-505/use-rotating-mailbox-in-nox)

## Proposed Changes
Call `push_mailbox` instead of `list_push_string` to store trigger events

## Screenshots (if applicable)
[Add any relevant screenshots or animated GIFs to showcase the changes.]

## Additional Notes
[Provide any additional information or context that may be helpful for the reviewer.]

## Checklist
- [x] The code follows the project's coding conventions and style guidelines.
- [x] All tests related to the changes have passed successfully.
- [x] Documentation has been updated to reflect the changes (if applicable).
- [x] All new and existing unit tests have passed.
- [x] I have self-reviewed my code and ensured its quality.
- [x] I have added/updated necessary comments to aid understanding.

## Reviewer Checklist
- [ ] Code has been reviewed for quality and adherence to [guidelines](https://doc.rust-lang.org/1.0.0/style/README.html).
- [ ] Tests have been reviewed and are sufficient to validate the changes.
- [ ] Documentation has been reviewed and is up to date.
- [ ] Any questions or concerns have been addressed.

### CODE REVIEW

**Review by folex — APPROVED** [review]

**Comment by kmd-fl** [comment]
You also need to update the spell service version.

What would happen with old spells? They don't have this function. We don't update the services of existing spells.

**Comment by justprosh** [comment]
> You also need to update the spell service version.
> 
> What would happen with old spells? They don't have this function. We don't update the services of existing spells.

@kmd-fl i waited for release of new spell version

**Comment by justprosh** [comment]
@kmd-fl oh, i got your concern 😅

**Comment by justprosh** [comment]
@kmd-fl I will provide a fallback if `push_mailbox` fails and will write directly for KV

**Pull request merged**
