### PR TITLE
feat(log): custom log format [fixes NET-724 NET-725]

### PR DESCRIPTION
**Pull request by gurinderu**
## Description
Added a custom log format.

## Motivation
Wants to format spans differently.

## Related Issue(s)
[NET-724](https://linear.app/fluence/issue/NET-724/rename-spans-to-modulefunction-format)
[NET-725](https://linear.app/fluence/issue/NET-725/make-span-names-in-logs-configurable)

## Screenshots 
Screenshot 2024-04-01 at 19 44 20

## Additional Notes
- Added non-blocking log appender

## Checklist
- [ ] The code follows the project's coding conventions and style guidelines.
- [ ] All tests related to the changes have passed successfully.
- [ ] Documentation has been updated to reflect the changes (if applicable).
- [ ] All new and existing unit tests have passed.
- [ ] I have self-reviewed my code and ensured its quality.
- [ ] I have added/updated necessary comments to aid understanding.

## Reviewer Checklist
- [ ] Code has been reviewed for quality and adherence to [guidelines](https://doc.rust-lang.org/1.0.0/style/README.html).
- [ ] Tests have been reviewed and are sufficient to validate the changes.
- [ ] Documentation has been reviewed and is up to date.
- [ ] Any questions or concerns have been addressed.

### CODE REVIEW

**Comment by kmd-fl** [comment]
Can you please explain the format in your screenshot?

**Comment by gurinderu** [comment]
> Can you please explain the format in your screenshot?

it is a default format with a custom spans format and the ability to hide the span list.

**Comment by kmd-fl** [comment]
> it is a default format with a custom spans format and the ability to hide the span list.

In your example, there are sometimes `{peer_id = ""}`, and sometimes there are not. I don't understand what is it, which peer id exactly and how do I add my custom data.

**Comment by gurinderu** [comment]
> In your example, there are sometimes `{peer_id = ""}`, and sometimes there are not. I don't understand what is it, which peer id exactly and how do I add my custom data.

ah, I got it. peer_id is the id passed inside current or parent spans. For now, you will see this information only in tests. It allows us to understand which node writes this line.

**Review by kmd-fl — APPROVED** [review]

**Pull request merged**
